FROM node:16-alpine

RUN apk update && apk add --no-cache --virtual .gyp python3 make g++
RUN ln -s /usr/bin/python3 /usr/bin/python && ln -s /usr/bin/pip3 /usr/bin/pip

EXPOSE 3000

COPY . .

RUN yarn add spid-cie-oidc

RUN yarn build

COPY docker/private.jwks.example.json private.jwks.json
COPY docker/public.jwks.example.json public.jwks.json
COPY docker/trust_marks.example.json trust_marks.json

ENTRYPOINT ["yarn", "start"]